enableGlobalCache: false
enableTelemetry: false
nodeLinker: node-modules

cacheFolder: ../../.yarn/cache

# this version was originally added as 4.4.0
# this file comes from berry--yarnpkg-cli-4.4.0.zip!/berry--yarnpkg-cli-4.4.0/packages/yarnpkg-cli/bin/yarn.js
# berry--yarnpkg-cli-4.4.0.zip comes from https://github.com/yarnpkg/berry/archive/refs/tags/@yarnpkg/cli/4.4.0.zip
# which can be found at https://github.com/yarnpkg/berry/releases
# (please add "-<version>" qualifier)
#
# the better way now is to:
#  - check new version of yarn using `corepack up` - this will update package.json's packageManager field
#  - call `yarn set version 4.9.2 --yarn-path` - this will download proper version, but because we use custom
#    path, be aware to copy the downloaded version to ../../.yarn/releases
yarnPath: ../../.yarn/releases/yarn-4.9.2.cjs
